### ISSUE TITLE
socket.error: [Errno 111] Connection refused [JIRA: CLIENTS-41]

### ISSUE THREAD

**Issue by riteshbabu** [basho/riak-python-client#375]
Hi 

I am using RIAK Python client for my project and RIAK amazon instance.I got this error while running my project and its related to RIAK instance.My error log is :- 
Traceback (most recent call last):
  File "ironjob/ai/index.py", line 36, in application
    returnval = mManager.process(api)
  File "ironjob/ai/ironMainManager.py", line 94, in process
    return self.mUserManager.process(listitem)
  File "ironjob/ai/ironUserManager.py", line 27, in process
    return self.userVerification(listitem)
  File "ironjob/ai/ironUserManager.py", line 62, in userVerification
    self.mCacheManager.addData(BUCKET_AI, datadict[KEY_SESSID], sessionData, cacheStart=1, cacheEnd=3, timeout=60)
  File "ironjob/ai/ironCacheManager.py", line 55, in addData
    self.mRiakClient.addData(bucket, key, dataVals, nestedKey=innerKey, timeout=timeout)
  File "ironjob/ai/ironRiakClient.py", line 53, in addData
    currentData = {} if bucket.get(key).get_data() == None else bucket.get(key).get_data()
  File "build/bdist.linux-x86_64/egg/riak/bucket.py", line 326, in get
  File "build/bdist.linux-x86_64/egg/riak/riak_object.py", line 459, in reload
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 251, in get
  File "build/bdist.linux-x86_64/egg/riak/transports/feature_detect.py", line 76, in quorum_controls
  File "build/bdist.linux-x86_64/egg/riak/util.py", line 61, in **get**
  File "build/bdist.linux-x86_64/egg/riak/transports/feature_detect.py", line 95, in server_version
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 178, in _server_version
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 206, in get_server_info
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 528, in send_msg_code
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 559, in send_pkt
  File "build/bdist.linux-x86_64/egg/riak/transports/pbc.py", line 113, in maybe_connect
  File "build/bdist.linux-x86_64/egg/riak/transports/connection.py", line 166, in maybe_connect

  File "<string>", line 1, in connect
socket.error: [Errno 111] Connection refused

Please help me out.Thanks in advance.

**Comment by peanpanther** [comment]
Thanks you all. It also works fine for me.
