### ISSUE TITLE
Client can't switch to working node [JIRA: CLIENTS-254]

### ISSUE THREAD

**Issue by etarasenko** [basho/riak-python-client#400]
Client can't switch from broken node to working node when we using connection timeout.

For testing we need have a Riak node on localhost and any domain without Riak.
The following code should complete without exceptions.
```
from riak import RiakClient

# We need check many times, because a node will be chosen randomly
for i in xrange(100):
    RiakClient(
        protocol='pbc',
        transport_options={'timeout': 1},  # timeout in seconds!!!
        nodes=[{'host': 'basho.com'}, {'host': 'localhost'}]
    ).ping()
```

**Comment by javajolt** [comment]
What errors are you seeing, @etarasenko ?

**Comment by etarasenko** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/client/transport.py", line 196, in wrapper
    return self._with_retries(pool, thunk)
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/client/transport.py", line 138, in _with_retries
    return fn(transport)
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/client/transport.py", line 194, in thunk
    return fn(self, transport, *args, **kwargs)
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/client/operations.py", line 136, in ping
    return transport.ping()
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/transports/pbc/transport.py", line 115, in ping
    msg_code, msg = self._request(MSG_CODE_PING_REQ)
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/transports/pbc/connection.py", line 55, in _request
    self._send_msg(msg_code, msg)
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/transports/pbc/connection.py", line 74, in _send_msg
    self._connect()
  File "/home/etarasenko/projects/riak/env/local/lib/python2.7/site-packages/riak/transports/pbc/connection.py", line 220, in _connect
    self._timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.timeout: timed out
```

**Comment by javajolt** [comment]
@etarasenko I'm a bit confused.  It seems to be doing what it's intended to be doing: timing out if it cannot connect.  All that's being done is [socket.settimeout()](https://docs.python.org/2/library/socket.html#socket.socket.settimeout).  You just need to handle the timeout exception.

You were expecting the client to silently switch to another host?

**Comment by etarasenko** [comment]
I have too long timeout without option ```transport_options={'timeout': 1}``` about 3-5 minutes.
I can't handle exception in my code because I can't control order of Riak nodes in pool for switching to another.

But I using the following monkey patch for fixing this bug:
```
# Monkey patch official python riak client
# for correct switching to new node on timeout
from riak.transports import http
http.CONN_CLOSED_ERRORS += (socket.timeout, )
```

Yes, I'm expecting switch to another node.

**Comment by javajolt** [comment]
Looks like you can do the same thing with Protocol Buffers:
```
from riak.transports import pbc
pbc.CONN_CLOSED_ERRORS += (socket.timeout, )
```
I'm a bit loathe to change this as the default behavior as others might be expecting an exception.

**Comment by etarasenko** [comment]
I'm closing the issue if you don't want change this behavior but for me it's bug when working with Riak cluster.

**Comment by javajolt** [comment]
@etarasenko I'm surprised that you got your change to work with HTTP.  I'm finding when I test it that I get connection errors instead of timeout errors.  On the HTTP side of things, it looks like it interrogates the server when setting up the connection pool.  I have a pretty simple fix for PBC, however.
